name: synthesis_project_env
channels:
  - conda-forge  # Prioritize conda-forge for faster installs
dependencies:
  - python=3.11
  - numpy       # Let Conda pick a compatible version
  - pandas
  - scipy
  - scikit-learn
  - matplotlib