name: synthesis_project_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pip        # Include pip so you can install pip-only packages
  - pip:
      - streamlit
      - gspread
      - oauth2client
      - Flask
      - google-api-python-client
      - paho-mqtt
